version: '3.8'

services:
  oci-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID:-ociprodet}
      - KEYCLOAK_CLIENT_AUTH_METHOD=${KEYCLOAK_CLIENT_AUTH_METHOD:-none}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  default:
    name: oci-network