CREATE TABLE app_file (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_path VARCHAR2(1024) NOT NULL,
    file_name VARCHAR2(255) NOT NULL,
    creation_started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    creation_finished_at TIMESTAMP WITH TIME ZONE NULL,
    file_size_bytes NUMBER(19, 0) NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_app_file_finished_after_started CHECK (
        creation_finished_at IS NULL OR creation_finished_at >= creation_started_at
    ),
    CONSTRAINT ck_app_file_size_nonnegative CHECK (
        file_size_bytes IS NULL OR file_size_bytes >= 0
    )
);

CREATE INDEX ix_app_file_path_name ON app_file (storage_path, file_name);
CREATE INDEX ix_app_file_started_at ON app_file (creation_started_at);

GRANT SELECT, INSERT, UPDATE, DELETE ON app_file TO ${appUser};
