CREATE TABLE app_generation (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requested_count NUMBER(10, 0) NOT NULL,
    generation_started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    generation_finished_at TIMESTAMP WITH TIME ZONE NULL,
    created_count NUMBER(10, 0) NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_app_generation_counts CHECK (
        requested_count >= 0 AND (created_count IS NULL OR created_count >= 0)
    ),
    CONSTRAINT ck_app_generation_finished_after_started CHECK (
        generation_finished_at IS NULL OR generation_finished_at >= generation_started_at
    )
);

CREATE INDEX ix_app_generation_started_at ON app_generation (generation_started_at);

ALTER TABLE app_file ADD generation_id NUMBER NULL;
CREATE INDEX ix_app_file_generation_id ON app_file (generation_id);
ALTER TABLE app_file ADD CONSTRAINT fk_app_file_generation
    FOREIGN KEY (generation_id) REFERENCES app_generation (id) ON DELETE SET NULL;

GRANT SELECT, INSERT, UPDATE, DELETE ON app_generation TO ${appUser};
